name: V2Ray Link Cleaner

on:
  schedule:
    - cron: '0 */5 * * *'      # هر ۵ ساعت یکبار
  workflow_dispatch:            # اجازه اجرای دستی

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # رفع اخطار Node.js

jobs:
  run-checker:
    runs-on: ubuntu-latest
    permissions:
      contents: write            # اجازه نوشتن در مخزن (برای push)

    steps:
      - name: دریافت کد از مخزن
        uses: actions/checkout@v4

      - name: نصب پایتون
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: نصب کتابخانه‌های مورد نیاز
        run: |
          python -m pip install --upgrade pip
          pip install requests colorama

      - name: اجرای چکر لینک‌ها
        run: python sub_link_checker.py

      - name: ذخیره خودکار فایل خروجی در مخزن
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add cleaned_configs.txt
          git diff --staged --quiet || git commit -m "Auto-update cleaned configs - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
